- name: prepare config directory
  file: path={{ item }}/autoload state=directory recurse=Yes
  with_items:
    - ~/.vim/
    - ~/.config/nvim
  tags: [dotfiles, vim]

- name: install vim-plug
  get_url:
    dest: "{{ item }}/autoload/plug.vim"
    url: 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  with_items:
    - ~/.vim/
    - ~/.config/nvim/
  tags: [dotfiles, vim]

- name: nvim config
  file: src={{ playbook_dir }}/files/vimrc dest=~/.config/nvim/init.vim state=link force=true
  tags: [dotfiles, vim]

- name: vim config
  file: src={{ playbook_dir }}/files/vimrc dest=~/.vimrc state=link force=true
  tags: [dotfiles, vim]
